### PR TITLE
Expand Remote and Cluster options

### LINKED ISSUE #361: Please add failure-detector to the fluent API
We are trying to update our application to use the Fluent API for configuration and after asking about this Aaron suggested creating an issue for it.

We would like to be able to configure the following via the Fluent API

cluster
{
    failure-detector
    {
        implementation-class="Akka.Remote.DeadlineFailureDectector.Akka.Remote"
        acceptable-heartbeat-pause = 300s
        heartbeat-interval = 2s
    }
}

### PR DESCRIPTION
**Pull request by Arkatufus**
Fixes #361

## Changes

* Add TransportFailureDetector property to RemoteOptions
* Add WatchFailureDetector property to RemoteOptions
* Add SendBufferSize property to RemoteOptions
* Add ReceiveBufferSize property to RemoteOptions
* Add MaxFrameSize property to RemoteOptions
* Add FailureDetector property to ClusterOptions

### CODE REVIEW

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Comment by stevemesser** [comment]
The FailureDetector property added to ClusterOptions only allows for one of the two options

**Comment by Aaronontheweb** [comment]
> The FailureDetector property added to ClusterOptions only allows for one of the two options

There's only one FailureDetector used in Akka.Cluster - it's Akka.Remote that has two different ones (one for transport, one for failure detector.)

**Comment by stevemesser** [comment]
I guess I am not understanding the relationship between the HOCON and where the failure detector is. In the HOCON shown it appears to me that the failure detector is part of cluster configuration but it seems you are saying its part of remoting.

Failure to Launch

**Pull request merged**
